services:
  dockge:
    image: louislam/dockge:1
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
{{#ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/ports}}
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKGE_STACKS_DIR=/stacks