services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: {{container_name}}
    restart: unless-stopped
    environment:
      - PUID={{puid}}
      - PGID={{pgid}}
      - TZ=Asia/Shanghai
    ports:
      - "{{http_port}}:5055"
    volumes:
      - {{config_dir}}:/config