services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:80"
    volumes:
      - {{data_dir}}:/data
    environment:
      - PUID={{puid}}
      - PGID={{pgid}}
      - TZ=Asia/Shanghai