services:
  aria2:
    image: p3terx/aria2-pro:latest
    container_name: {{container_name}}
    restart: unless-stopped
    environment:
      - TZ={{timezone}}
      - RPC_SECRET={{rpc_secret}}
    ports:
{{#ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/ports}}
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
