services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:5212"
    volumes:
      - {{data_dir}}:/cloudreve/data
