services:
  lanraragi:
    image: difegue/lanraragi:latest
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:9999"
    volumes:
      - {{data_dir}}:/home/lnr/data
      - {{content_dir}}:/home/lnr/content
    environment:
      - TZ=Asia/Shanghai