services:
  gotify:
    image: gotify/server:latest
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:80"
    volumes:
      - {{data_dir}}:/app/data
    environment:
      - PUID={{puid}}
      - PGID={{pgid}}