services:
  nextcloud:
    image: nextcloud:latest
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:80"
    volumes:
      - {{data_dir}}:/var/www/html
    environment:
      - PUID={{puid}}
      - PGID={{pgid}}
      - TZ=Asia/Shanghai