services:
  lucky:
    image: zhz1021/lucky:latest
    container_name: {{container_name}}
    restart: always
    network_mode: host
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
