services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: {{container_name}}
    restart: unless-stopped
    environment:
      - TZ={{timezone}}
      - PUID={{puid}}
      - PGID={{pgid}}
    ports:
      - "{{http_port}}:9696"
    volumes:
      - {{config_dir}}:/config
