services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: {{container_name}}
    restart: unless-stopped
    environment:
      - TZ={{timezone}}
      - PUID={{puid}}
      - PGID={{pgid}}
    ports:
{{#ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/ports}}
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
