services:
  clouddrive2:
    image: cloudnas/clouddrive2:latest
    container_name: clouddrive2
    restart: unless-stopped
    environment:
      - TZ={{timezone}}
      - CLOUDDRIVE_HOME=/Config
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
    devices:
      - /dev/fuse:/dev/fuse
    pid: host
    privileged: true
    network_mode: host
