services:
  wikijs:
    image: requarks/wiki:2
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:3000"
    volumes:
      - {{data_dir}}:/wiki/data
    environment:
      - TZ=Asia/Shanghai
      - DB_TYPE=sqlite
      - DB_FILEPATH=/wiki/data/db.sqlite
