services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: {{container_name}}-hbbs
    restart: unless-stopped
    depends_on:
      - hbbr
    ports:
{{#hbbs_ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/hbbs_ports}}
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
    command: hbbs

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: {{container_name}}-hbbr
    restart: unless-stopped
    ports:
{{#hbbr_ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/hbbr_ports}}
    volumes:
{{#volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/volumes}}
    command: hbbr
