services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: {{container_name}}
    restart: unless-stopped
    environment:
      - PUID={{puid}}
      - PGID={{pgid}}
      - TZ=Asia/Shanghai
    ports:
      - "{{http_port}}:8181"
    volumes:
      - {{config_dir}}:/config