services:
  memos:
    image: neosmemo/memos:stable
    container_name: {{container_name}}
    restart: unless-stopped
    ports:
      - "{{http_port}}:5230"
    volumes:
      - {{data_dir}}:/var/opt/memos
    environment:
      - TZ=Asia/Shanghai
