services:
  bookstack-db:
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - TZ={{timezone}}
      - PUID={{puid}}
      - PGID={{pgid}}
      - MYSQL_ROOT_PASSWORD={{db_root_password}}
      - MYSQL_DATABASE={{db_name}}
      - MYSQL_USER={{db_user}}
      - MYSQL_PASSWORD={{db_password}}
    volumes:
{{#db_volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/db_volumes}}

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: {{container_name}}
    restart: unless-stopped
    depends_on:
      - bookstack-db
    ports:
{{#ports}}
      - "{{host}}:{{container}}/{{protocol}}"
{{/ports}}
    volumes:
{{#app_volumes}}
      - {{source}}:{{target}}:{{mode}}
{{/app_volumes}}
    environment:
      - TZ={{timezone}}
      - PUID={{puid}}
      - PGID={{pgid}}
      - APP_URL={{app_url}}
      - APP_KEY={{app_key}}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER={{db_user}}
      - DB_PASS={{db_password}}
      - DB_NAME={{db_name}}
